<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Tests for WaitForNuGetPackage.</Description>
    <OutputType>Exe</OutputType>
    <RootNamespace>MartinCostello.WaitForNuGetPackage</RootNamespace>
    <TargetFramework>net11.0</TargetFramework>
    <UserSecretsId>MartinCostello.WaitForNuGetPackage</UserSecretsId>
    <UseDefaultCodeAnalysisRuleSet>true</UseDefaultCodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WaitForNuGetPackage\WaitForNuGetPackage.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="Spectre.Console.Cli.Testing" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverageRunSettings>$(MSBuildThisFileDirectory)tests.runsettings</CoverageRunSettings>
    <Threshold>80,75,85</Threshold>
  </PropertyGroup>
</Project>
