name: code-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  schedule:
    - cron: '0 6 * * MON'
  workflow_dispatch:

# HACK Disable additional code analysis as a workaround for https://github.com/dotnet/roslyn/issues/70368.
# See https://github.com/App-vNext/Polly/pull/1708 for inspiration.
env:
  AnalysisMode: "None"
  EnableNETAnalyzers: "false"

permissions:
  actions: read
  contents: read

jobs:
  code-ql:

    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'
        queries: security-and-quality

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: '/language:csharp'
